# Generated by Django 4.0.6 on 2022-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artist_bio_artist_dateofbirth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
